version: '3.2'

services:
  postgres:
    container_name: postgres
    image: postgres
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: taskmanager
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile-web-localhost
    image: endpoint:localhost
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  scheduler:
    build: 
      context: .
      dockerfile: ./Dockerfile-scheduler-localhost
    image: scheduler:localhost
    restart: always
    expose:
      - "9090"
    depends_on:
      - web
  scope:
    image: weaveworks/scope:1.10.2
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
    depends_on:
      - scheduler

## Uncomment this if you want to use multi-stage docker build locally and start containers

# version: '3.2'

# services:
#   postgres:
#     container_name: postgres
#     image: postgres
#     expose:
#       - "5432"
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: taskmanager
#   web:
#     build: 
#       context: .
#       dockerfile: ./Dockerfile-web-compose
#     image: endpoint:compose
#     restart: always
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#   scheduler:
#     build: 
#       context: .
#       dockerfile: ./Dockerfile-scheduler-compose
#     image: scheduler:compose
#     restart: always
#     expose:
#       - "9090"
#     depends_on:
#       - web
#   scope:
#     image: weaveworks/scope:1.10.2
#     network_mode: "host"
#     pid: "host"
#     privileged: true
#     labels:
#       - "works.weave.role=system"
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock:rw"
#     command:
#       - "--probe.docker=true"

