FROM maven:3.6.0-jdk-8 as BUILD
RUN apt-get update && apt-get install
WORKDIR /home
COPY . /home
RUN mvn clean install -Pweb && mvn clean install -Pscheduler


FROM anapsix/alpine-java
WORKDIR /home
COPY --from=BUILD  /home/scheduler/target/scheduler-0.1-SNAPSHOT.jar /home/
CMD ["java", "-jar", "/home/scheduler-0.1-SNAPSHOT.jar"]


